### ISSUE TITLE
Criar pipeline

### ISSUE THREAD

**Issue by jemimad** [jemimad/den-bank#48]
Todo push na branch develop (ou merge request) deve iniciar a execução do pipeline 
de integração contínua que executará as seguintes ações:
- Resolver as dependências do projeto
- Buildar o sistema (compilar ou realizar checagem sintática)
- Executar testes unitários
  - Para esta ação você deve criar testes unitários no seu projeto, tendo pelo menos 1 teste para cada operação de cada tipo de conta.
- O push (ou merge request) não deve ser aceito, caso qualquer uma das ações do pipeline falhe

**Comment by carmems** [comment]
Issue resolvida em #49
